"""empty message

Revision ID: 016ac8854c18
Revises: 
Create Date: 2021-07-14 22:00:40.373783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "016ac8854c18"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "residencias",
        sa.Column("id_residencia", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=True),
        sa.Column("host_id", sa.Integer(), nullable=True),
        sa.Column("host_name", sa.String(length=150), nullable=True),
        sa.Column("neighbourhood", sa.String(length=150), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("room_type", sa.String(length=150), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("minimum_nights", sa.Integer(), nullable=True),
        sa.Column("number_of_reviews", sa.Integer(), nullable=True),
        sa.Column("last_review", sa.String(length=10), nullable=True),
        sa.Column("reviews_per_month", sa.Float(), nullable=True),
        sa.Column("calculated_host_listings_count", sa.Integer(), nullable=True),
        sa.Column("availability_365", sa.Integer(), nullable=True),
        sa.Column("neighbourhood_group", sa.String(length=150), nullable=True),
        sa.PrimaryKeyConstraint("id_residencia"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("residencias")
    # ### end Alembic commands ###
