"""empty message

Revision ID: eb88cf0e2fcd
Revises: fec7e3bfc8a7
Create Date: 2021-07-18 20:08:33.658542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb88cf0e2fcd"
down_revision = "fec7e3bfc8a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("residencias", sa.Column("like", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("residencias", "like")
    # ### end Alembic commands ###
